import type { PreflightPayload } from "./types";

export const samplePreflightPayload: PreflightPayload = {
  template: {
    schemaVersion: 2,
    templateId: "shirt-demo-one-size",
    version: "0.1.0-draft",
    masterFingerprint: "UNVERIFIED-DEMO-FINGERPRINT",
    masterSourceRef: "demo-master/成品母版.psd",
    document: {
      width: 6000,
      height: 6000,
      ppi: 150,
      colorMode: "rgb",
      bitDepth: 8,
      iccProfile: null,
    },
    garmentPieces: [
      { id: "piece-front", name: "前片" },
      { id: "piece-back", name: "后片" },
      { id: "piece-left-sleeve", name: "左袖" },
      { id: "piece-right-sleeve", name: "右袖" },
    ],
    artworkEntries: [
      {
        id: "entry-front",
        name: "前片入口",
        inputKey: "front",
        contentSourceId: "source-front",
        replacementLayerName: "REPLACE_ART",
        required: true,
        canvas: { width: 2400, height: 3200 },
        fit: { mode: "strict", anchor: { kind: "center" } },
      },
      {
        id: "entry-back",
        name: "后片入口",
        inputKey: "back",
        contentSourceId: "source-back",
        replacementLayerName: "REPLACE_ART",
        required: true,
        canvas: { width: 2400, height: 3200 },
        fit: { mode: "cover", anchor: { kind: "center" } },
      },
      {
        id: "entry-sleeves",
        name: "袖片共享入口",
        inputKey: "sleeves",
        contentSourceId: "source-sleeves",
        replacementLayerName: "REPLACE_ART",
        required: true,
        canvas: { width: 1800, height: 2400 },
        fit: { mode: "cover", anchor: { kind: "offset", x: 0, y: -24 } },
      },
    ],
    instances: [
      {
        id: "instance-front",
        garmentPieceId: "piece-front",
        artworkEntryId: "entry-front",
        layerPath: ["PRINT｜生产内容", "前片", "ART｜印花智能对象实例"],
      },
      {
        id: "instance-back",
        garmentPieceId: "piece-back",
        artworkEntryId: "entry-back",
        layerPath: ["PRINT｜生产内容", "后片", "ART｜印花智能对象实例"],
      },
      {
        id: "instance-left-sleeve",
        garmentPieceId: "piece-left-sleeve",
        artworkEntryId: "entry-sleeves",
        layerPath: ["PRINT｜生产内容", "左袖", "ART｜印花智能对象实例"],
      },
      {
        id: "instance-right-sleeve",
        garmentPieceId: "piece-right-sleeve",
        artworkEntryId: "entry-sleeves",
        layerPath: ["PRINT｜生产内容", "右袖", "ART｜印花智能对象实例"],
      },
    ],
    output: {
      capabilityProfileId: "UNVERIFIED-DEMO-OUTPUT",
      productionMode: "pieces",
      preview: {
        id: "preview-composite",
        fileName: "预览.jpg",
        region: { x: 0, y: 0, width: 4800, height: 3600 },
        visibleLayerPaths: [["PREVIEW｜预览内容"]],
        markLayerPaths: [],
        maximumFileBytes: 80_000_000,
        profile: {
          format: "jpeg",
          compression: "jpeg-high",
          ppi: 72,
          colorMode: "rgb",
          bitDepth: 8,
          icc: { mode: "none" },
          background: { kind: "solid", color: "#ffffff" },
          includeGuides: false,
          includeMarks: false,
        },
      },
      production: (
        [
          ["front", "piece-front", "前片", 0, 0, 2400, 3200],
          ["back", "piece-back", "后片", 2400, 0, 2400, 3200],
          ["left-sleeve", "piece-left-sleeve", "左袖", 0, 3200, 1800, 2400],
          [
            "right-sleeve",
            "piece-right-sleeve",
            "右袖",
            1800,
            3200,
            1800,
            2400,
          ],
        ] as const
      ).map(([id, garmentPieceId, name, x, y, width, height]) => ({
        id: `production-${id}`,
        productionKind: "piece" as const,
        garmentPieceId,
        fileName: `${name}.png`,
        region: { x, y, width, height },
        visibleLayerPaths: [["PRINT｜生产内容", name]],
        markLayerPaths: [["MARKS｜工艺标记", name]],
        maximumFileBytes: 80_000_000,
        profile: {
          format: "png" as const,
          compression: "lossless" as const,
          ppi: 150,
          colorMode: "rgb" as const,
          bitDepth: 8 as const,
          icc: { mode: "none" as const },
          background: { kind: "transparent" as const },
          includeGuides: false,
          includeMarks: false,
        },
      })),
    },
  },
  groups: [
    {
      name: "款式001-蓝花",
      files: [
        {
          name: "front.png",
          width: 2400,
          height: 3200,
          ppi: 72,
          sourceRef: "款式001-蓝花/front.png",
          fingerprint: "demo-front-blue",
        },
        {
          name: "back.jpg",
          width: 3000,
          height: 3000,
          ppi: 300,
          sourceRef: "款式001-蓝花/back.jpg",
          fingerprint: "demo-back-blue",
        },
        {
          name: "sleeves.png",
          width: 1800,
          height: 2600,
          ppi: 150,
          sourceRef: "款式001-蓝花/sleeves.png",
          fingerprint: "demo-sleeves-blue",
        },
      ],
    },
    {
      name: "款式 002（待补图）",
      files: [
        {
          name: "front.png",
          width: 2400,
          height: 3200,
          ppi: 300,
          sourceRef: "款式002/front.png",
          fingerprint: "demo-front-pending",
        },
        {
          name: "sleeves.jpg",
          width: 1800,
          height: 2400,
          ppi: 72,
          sourceRef: "款式002/sleeves.jpg",
          fingerprint: "demo-sleeves-pending",
        },
        { name: "说明.txt" },
      ],
    },
  ],
};
